/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_lbovolini_crowd_example_nativelib_Native */

#ifndef _Included_com_github_lbovolini_crowd_example_nativelib_Native
#define _Included_com_github_lbovolini_crowd_example_nativelib_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_lbovolini_crowd_example_nativelib_Native
 * Method:    say
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_lbovolini_crowd_example_nativelib_Native_say
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
